### PR TITLE
add kick on bad name to fellowshipbot.py

### PR DESCRIPTION
**Pull request by judge2020**
image

### CODE REVIEW

**Comment by judge2020** [comment]
also, would anyone like me to run the bot? i have a linux server with only 14% memory used so i'd be happy to host it

**Comment by Chandler255** [comment]
Judge, I was going to host it with my server

**Comment by judge2020** [comment]
@Chandler255 that's fine, i was just offering :stuck_out_tongue:
but when will you start hosting it?...

**Comment by captain-** [comment]
We already have a script that kicks bad names from the channel.

**Comment by judge2020** [comment]
@captain- oh ya, i forgot! i gave snow that mirc script long ago so it's already there

**Pull request closed without merging**
